export const FETCH_SEARCH_TRIPS = 'FETCH_SEARCH_TRIPS';
export const FETCH_SEARCH_FAILED = 'FETCH_SEARCH_FAILED';
export const GET_ERRORS = 'GET_ERRORS';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
// constants for profile
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';
export const PROFILE_UPDATE_VALUE = 'PROFILE_UPDATE_VALUE';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_SUCCESS';
//
// constants for the subscrptions
export const FETCH_SUBSCRIPTIONS_BEGIN = 'FETCH_SUBSCRIPTIONS_BEGIN';
export const FETCH_SUBSCRIPTIONS_SUCCESS = 'FETCH_SUBSCRIPTIONS_SUCCESS';
export const FETCH_SUBSCRIPTIONS_FAILURE = 'FETCH_SUBSCRIPTIONS_FAILURE';

export const FETCH_ONE_TRIP_SUCCESS = 'FETCH_ONE_TRIP_SUCCESS';
export const FETCH_ONE_TRIP_BEGIN = 'FETCH_ONE_TRIP_BEGIN';
export const FETCH_ONE_TRIP_FAILURE = 'FETCH_ONE_TRIP_FAILURE';

// constants for myTrips
export const SHOW_MY_TRIPS_SUCCESS = 'SHOW_MY_TRIPS_SUCCESS';
export const SHOW_MY_TRIPS_FAILED = 'SHOW_MY_TRIPS_FAILED';
