export const FETCH_SEARCH_TRIPS = 'FETCH_SEARCH_TRIPS';

// constants for profile
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';
export const PROFILE_UPDATE_VALUE = 'PROFILE_UPDATE_VALUE';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_SUCCESS';
//
