export const FETCH_SEARCH_TRIPS = 'FETCH_SEARCH_TRIPS';
export const FETCH_SEARCH_FAILED = 'FETCH_SEARCH_FAILED';
export const GET_ERRORS = 'GET_ERRORS';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';

// constants for the subscrptions
export const FETCH_SUBSCRIPTIONS_BEGIN = 'FETCH_SUBSCRIPTIONS_BEGIN';
export const FETCH_SUBSCRIPTIONS_SUCCESS = 'FETCH_SUBSCRIPTIONS_SUCCESS';
export const FETCH_SUBSCRIPTIONS_FAILURE = 'FETCH_SUBSCRIPTIONS_FAILURE';

export const FETCH_ONE_TRIP_SUCCESS = 'FETCH_ONE_TRIP_SUCCESS';
export const FETCH_ONE_TRIP_BEGIN = 'FETCH_ONE_TRIP_BEGIN';
export const FETCH_ONE_TRIP_FAILURE = 'FETCH_ONE_TRIP_FAILURE';

// myTrips
export const SHOW_MY_TRIPS_SUCCESS = 'SHOW_MY_TRIPS_SUCCESS';
export const SHOW_MY_TRIPS_FAILED = 'SHOW_MY_TRIPS_FAILED';

// tripCreate
export const TRIP_CREATE_SUCCESS = 'TRIP_CREATE_SUCCSESS';
export const TRIP_CREATE_FAILED = 'TRIP_CREATE_FAILED';
