export const FETCH_SEARCH_TRIPS = 'FETCH_SEARCH_TRIPS';
export const FETCH_SEARCH_FAILED = 'FETCH_SEARCH_FAILED';
export const GET_ERRORS = 'GET_ERRORS';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
