// Reducing Boilerplate
const SEND_REQUEST_PROFILE = 'REQUEST_TO_PROFILE';
const SHOW_PROFILE = 'SHOW_PROFILE';
const SUCCESS_RESPONSE_TO_PROFILE = 'SUCCESS_RESPONSE_TO_PROFILE';
// {
//   type: SEND_REQUEST_PROFILE,

// }
export { SEND_REQUEST_PROFILE, SHOW_PROFILE, SUCCESS_RESPONSE_TO_PROFILE };
